#!/usr/bin/env python3
#
# Copyright (C) 2026 Erfan Abdi <erfangplus@gmail.com>
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
# http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

"""Fetch the latest suggested APKs listed in a txt file from F-Droid repos
and generate Android.bp, product.mk and versions.txt for an AOSP build."""

import argparse
import gzip
import hashlib
import json
import os
import re
import shutil
import struct
import subprocess
import sys
import tempfile
import urllib.parse
import urllib.request
import zipfile
from xml.sax.saxutils import quoteattr

ARCH_ABI = {
    "arm64": "arm64-v8a",
    "arm": "armeabi-v7a",
    "x86_64": "x86_64",
    "x86": "x86",
}
ARCHES = ["all"] + list(ARCH_ABI)
PARTITIONS = {
    "system_ext": "system_ext_specific",
    "product": "product_specific",
}
COPY_OUT = {
    "system_ext": "$(TARGET_COPY_OUT_SYSTEM_EXT)",
    "product": "$(TARGET_COPY_OUT_PRODUCT)",
}
APP_DIRS = {"app": "app", "priv": "priv-app"}
TYPES = ["app", "priv"]
NAME_RE = re.compile(r"^[A-Za-z0-9_.-]+$")
LOCK_FIELDS = ["name", "arch", "package", "versionName", "versionCode",
               "signer", "sha256", "repo"]
USER_AGENT = "android_vendor_fdroid/1.0"
HEADER = "Generated by android_vendor_fdroid/fdroid_sync.py. DO NOT EDIT."

# Old repos sign their index with SHA1withRSA, which current JDKs reject.
JAVA_SECURITY = "jdk.jar.disabledAlgorithms=MD2, MD5, RSA keySize < 1024\n"


def die(msg):
    sys.exit("ERROR: " + msg)


def warn(msg):
    print("WARNING: " + msg, file=sys.stderr)


class Entry:
    def __init__(self, lineno, package, name, partition, arch, cert, type_,
                 repo):
        self.lineno = lineno
        self.package = package
        self.name = name
        self.partition = partition
        self.arch = arch
        self.cert = cert
        self.type = type_
        self.repo = repo


def parse_list(path):
    """Return ({name: [Entry]}, {name: [overridden AOSP modules]},
    {names to install as stub})."""
    entries = []
    overrides = {}
    stubs = {}
    section = "apps"
    with open(path) as f:
        for lineno, line in enumerate(f, 1):
            line = line.split("#", 1)[0].strip()
            if not line:
                continue
            if line.startswith("[") and line.endswith("]"):
                section = line[1:-1].strip()
                if section not in ("apps", "overrides", "stubs"):
                    die(f"{path}:{lineno}: unknown section [{section}]")
                continue
            cols = line.split()
            if section == "overrides":
                if len(cols) < 2:
                    die(f"{path}:{lineno}: expected <name> <aosp module>...")
                for c in cols:
                    if not NAME_RE.match(c):
                        die(f"{path}:{lineno}: invalid module name '{c}'")
                overrides.setdefault(cols[0], []).append((lineno, cols[1:]))
                continue
            if section == "stubs":
                for c in cols:
                    stubs[c] = lineno
                continue
            if len(cols) != 7:
                die(f"{path}:{lineno}: expected 7 columns "
                    f"(package name partition arch cert type repo), "
                    f"got {len(cols)}")
            e = Entry(lineno, *cols)
            where = f"{path}:{lineno}"
            if not NAME_RE.match(e.name):
                die(f"{where}: invalid module name '{e.name}'")
            if e.partition not in PARTITIONS:
                die(f"{where}: partition must be one of "
                    f"{', '.join(PARTITIONS)}")
            if e.arch not in ARCHES:
                die(f"{where}: arch must be one of {', '.join(ARCHES)}")
            if e.type not in TYPES:
                die(f"{where}: type must be one of {', '.join(TYPES)}")
            if not NAME_RE.match(e.cert):
                die(f"{where}: invalid cert '{e.cert}'")
            if not e.repo.startswith("https://"):
                die(f"{where}: repo must be an https:// URL")
            entries.append(e)

    modules = {}
    for e in entries:
        mod = modules.setdefault(e.name, [])
        for o in mod:
            if o.arch == e.arch:
                die(f"{path}:{e.lineno}: duplicate {e.name} [{e.arch}] "
                    f"(see line {o.lineno})")
            for attr in ("package", "partition", "cert", "type", "repo"):
                if getattr(o, attr) != getattr(e, attr):
                    die(f"{path}:{e.lineno}: {attr} of {e.name} differs from "
                        f"line {o.lineno}")
        mod.append(e)

    resolved = {}
    for name, items in overrides.items():
        for lineno, targets in items:
            if name not in modules:
                die(f"{path}:{lineno}: override for unknown app '{name}'")
            if name in targets:
                die(f"{path}:{lineno}: {name} cannot override itself")
            resolved.setdefault(name, set()).update(targets)
    for name, lineno in stubs.items():
        if name not in modules:
            die(f"{path}:{lineno}: stub for unknown app '{name}'")
        if modules[name][0].cert != "presigned":
            die(f"{path}:{lineno}: only presigned apps can be stubs, the "
                f"stub and the .apk.gz must have the same signature")
        if len(modules[name]) > 1:
            die(f"{path}:{lineno}: stubs support one APK only, list a "
                f"single arch for {name}")
    return (modules, {n: sorted(t) for n, t in resolved.items()},
            set(stubs))


def split_repo(url):
    """Return (base_url, fingerprint or None) for an F-Droid repo link."""
    u = urllib.parse.urlsplit(url)
    query = urllib.parse.parse_qs(u.query)
    fp = query.get("fingerprint", [None])[0]
    if fp:
        fp = fp.replace(":", "").lower()
        if not re.fullmatch(r"[0-9a-f]{64}", fp):
            die(f"invalid fingerprint in {url}")
    base = urllib.parse.urlunsplit((u.scheme, u.netloc, u.path.rstrip("/"),
                                    "", ""))
    return base, fp


def download(url, dest):
    req = urllib.request.Request(url, headers={"User-Agent": USER_AGENT})
    h = hashlib.sha256()
    try:
        with urllib.request.urlopen(req, timeout=120) as r, \
                open(dest, "wb") as f:
            while chunk := r.read(1 << 20):
                h.update(chunk)
                f.write(chunk)
    except OSError as ex:
        die(f"failed to download {url}: {ex}")
    return h.hexdigest()


def sha256_file(path):
    h = hashlib.sha256()
    with open(path, "rb") as f:
        while chunk := f.read(1 << 20):
            h.update(chunk)
    return h.hexdigest()


def verify_index_jar(jar, fingerprint, tmpdir):
    props = os.path.join(tmpdir, "java.security")
    with open(props, "w") as f:
        f.write(JAVA_SECURITY)
    java_opt = "-J-Djava.security.properties=" + props

    r = subprocess.run(["jarsigner", java_opt, "-verify", jar],
                       capture_output=True, text=True)
    out = r.stdout + r.stderr
    if r.returncode != 0 or "jar verified." not in out \
            or "unsigned entries" in out:
        die(f"index signature verification failed for {jar}:\n{out}")

    r = subprocess.run(["keytool", java_opt, "-printcert", "-jarfile", jar],
                       capture_output=True, text=True)
    signers = {m.replace(":", "").lower() for m in
               re.findall(r"SHA256:\s*([0-9A-Fa-f:]{95})", r.stdout)}
    if signers != {fingerprint}:
        die(f"index signer {', '.join(sorted(signers)) or '(none)'} does not "
            f"match fingerprint {fingerprint}")


class Repo:
    def __init__(self, url, tmpdir):
        self.base, fingerprint = split_repo(url)
        jar = os.path.join(tmpdir, hashlib.sha1(url.encode()).hexdigest()
                           + ".jar")
        print(f"- Fetching index {self.base}")
        download(self.base + "/index-v1.jar", jar)
        if fingerprint:
            verify_index_jar(jar, fingerprint, tmpdir)
            print("  index signature: VALID")
        else:
            warn(f"no fingerprint for {self.base}, index signature not "
                 f"verified")
        with zipfile.ZipFile(jar) as z:
            index = json.loads(z.read("index-v1.json"))
        os.remove(jar)
        self.apps = {a["packageName"]: a for a in index.get("apps", [])}
        self.packages = index.get("packages", {})


def abis_of(apk):
    return set(apk.get("nativecode") or [])


def pick_apk(repo, entry, old_signer):
    """Pick the suggested APK for entry.package that runs on entry.arch."""
    apks = repo.packages.get(entry.package)
    app = repo.apps.get(entry.package)
    if not apks or not app:
        die(f"{entry.package} not found in {repo.base}")

    suggested = app.get("suggestedVersionCode")
    version_name = None
    if suggested is not None:
        for a in apks:
            if a["versionCode"] == int(suggested):
                version_name = a["versionName"]
                break
    if version_name is None:
        warn(f"{entry.package}: no suggested version in index, using the "
             f"highest versionCode")
        version_name = max(apks, key=lambda a: a["versionCode"])["versionName"]
    same_version = [a for a in apks if a["versionName"] == version_name]

    if entry.arch == "all":
        # Universal: no native code, or covers every ABI this version ships.
        shipped = set().union(*(abis_of(a) for a in same_version))
        candidates = [a for a in same_version
                      if not abis_of(a) or abis_of(a) >= shipped]
        if not candidates:
            die(f"{entry.name}: {entry.package} {version_name} has no "
                f"universal APK (split ABIs: {', '.join(sorted(shipped))}), "
                f"list one line per arch instead of 'all'")
    else:
        abi = ARCH_ABI[entry.arch]
        candidates = [a for a in same_version
                      if not abis_of(a) or abi in abis_of(a)]
        if not candidates:
            die(f"{entry.name}: {entry.package} {version_name} has no APK "
                f"for {abi}")

    # Same version may be published under several signers (e.g. upstream
    # reproducible builds). Stick to the one we shipped before, so installed
    # apps keep receiving updates from F-Droid.
    signers = {a.get("signer") for a in candidates}
    if old_signer and old_signer in signers:
        candidates = [a for a in candidates if a.get("signer") == old_signer]
    elif old_signer:
        msg = (f"{entry.name} [{entry.arch}]: signer changed from "
               f"{old_signer} to {', '.join(sorted(signers))}")
        if entry.cert == "presigned":
            die(msg + "; devices would no longer accept updates. Remove the "
                "row from versions.txt in the output repo to accept it")
        warn(msg)
    elif app.get("preferredSigner") in signers:
        candidates = [a for a in candidates
                      if a.get("signer") == app["preferredSigner"]]

    return max(candidates, key=lambda a: a["versionCode"])


def read_lock(path):
    lock = {}
    if not os.path.exists(path):
        return lock
    with open(path) as f:
        for line in f:
            if line.startswith("#") or not line.strip():
                continue
            row = dict(zip(LOCK_FIELDS, line.rstrip("\n").split("\t")))
            lock[(row["name"], row["arch"])] = row
    return lock


def apk_relpath(entry):
    suffix = "" if entry.arch == "all" else "_" + entry.arch
    return f"apps/{entry.name}/{entry.name}{suffix}.apk"


def privapp_relpath(name):
    return f"apps/{name}/privapp-permissions-{name}.xml"


# Binary XML (AXML) chunk types and android: attribute resource ids.
AXML_STRING_POOL = 0x0001
AXML_RESOURCE_MAP = 0x0180
AXML_START_ELEMENT = 0x0102
ATTR_NAME = 0x01010003
ATTR_REQUIRED = 0x0101028E
TYPE_STRING = 0x03
TYPE_BOOLEAN = 0x12
NO_INDEX = 0xFFFFFFFF


def _axml_strings(data, off):
    count, _, flags, strings_start = struct.unpack_from("<IIII", data, off + 8)
    utf8 = flags & 0x100
    base = off + strings_start
    strings = []
    for i in range(count):
        pos = base + struct.unpack_from("<I", data, off + 28 + 4 * i)[0]
        if utf8:
            for _ in range(2):  # UTF-16 length, then UTF-8 byte length
                n = data[pos]
                pos += 1
                if n & 0x80:
                    n = ((n & 0x7F) << 8) | data[pos]
                    pos += 1
            strings.append(data[pos:pos + n].decode("utf-8", "replace"))
        else:
            n = struct.unpack_from("<H", data, pos)[0]
            pos += 2
            if n & 0x8000:
                n = ((n & 0x7FFF) << 16) | struct.unpack_from("<H", data,
                                                              pos)[0]
                pos += 2
            strings.append(data[pos:pos + 2 * n].decode("utf-16-le",
                                                        "replace"))
    return strings


def uses_libraries_of(apk_path):
    """Return {library: required} from the APK's <uses-library> tags."""
    with zipfile.ZipFile(apk_path) as z:
        data = z.read("AndroidManifest.xml")
    strings, resmap, libs = [], [], {}
    pos = struct.unpack_from("<H", data, 2)[0]
    while pos + 8 <= len(data):
        ctype, hsize, csize = struct.unpack_from("<HHI", data, pos)
        if csize < 8:
            break
        if ctype == AXML_STRING_POOL:
            strings = _axml_strings(data, pos)
        elif ctype == AXML_RESOURCE_MAP:
            resmap = list(struct.unpack_from(f"<{(csize - hsize) // 4}I",
                                             data, pos + hsize))
        elif ctype == AXML_START_ELEMENT:
            _, tag, astart, asize, acount = struct.unpack_from(
                "<IIHHH", data, pos + hsize)
            if strings[tag] == "uses-library":
                name, required = None, True
                for i in range(acount):
                    a = pos + hsize + astart + i * asize
                    _, aname, raw, _, _, dtype, value = struct.unpack_from(
                        "<IIIHBBI", data, a)
                    rid = resmap[aname] if aname < len(resmap) else None
                    if rid == ATTR_NAME or (rid is None
                                            and strings[aname] == "name"):
                        if raw != NO_INDEX:
                            name = strings[raw]
                        elif dtype == TYPE_STRING:
                            name = strings[value]
                    elif rid == ATTR_REQUIRED or (
                            rid is None and strings[aname] == "required"):
                        if dtype == TYPE_BOOLEAN:
                            required = value != 0
                        elif raw != NO_INDEX:
                            required = strings[raw] != "false"
                if name:
                    libs[name] = libs.get(name, False) or required
        pos += csize
    return libs


def preprocessed_issue(apk_path, privileged):
    """Mirror build/soong/scripts/check_prebuilt_presigned_apk.py: return
    why a preprocessed APK fails Soong's checks, or None. Soong also fails
    when skip_preprocessed_apk_checks is set on an APK without issues."""
    with zipfile.ZipFile(apk_path) as z, open(apk_path, "rb") as f:
        for i in z.infolist():
            is_so = i.filename.startswith("lib/") and i.filename.endswith(".so")
            if i.compress_type != zipfile.ZIP_STORED:
                if is_so:
                    return "compressed JNI libraries"
                if privileged and i.filename.endswith(".dex"):
                    return "compressed dex files and is privileged"
                continue
            # zipalign -c -p 4: stored data 4-byte aligned, .so page aligned
            f.seek(i.header_offset + 26)
            name_len, extra_len = struct.unpack("<HH", f.read(4))
            offset = i.header_offset + 30 + name_len + extra_len
            if offset % (4096 if is_so else 4):
                return "improper zip alignment"
    return None


def write_gz(src, dest):
    """Deterministic gzip, so unchanged APKs don't produce git diffs."""
    with open(src, "rb") as fi, open(dest + ".part", "wb") as raw, \
            gzip.GzipFile(filename="", mode="wb", fileobj=raw,
                          compresslevel=9, mtime=0) as fo:
        shutil.copyfileobj(fi, fo, 1 << 20)
    os.replace(dest + ".part", dest)


def permissions_of(apk):
    perms = set()
    for key in ("uses-permission", "uses-permission-sdk-23"):
        for p in apk.get(key) or []:
            perms.add(p[0] if isinstance(p, list) else p)
    return perms


def write_privapp_xml(path, package, perms):
    lines = ['<?xml version="1.0" encoding="utf-8"?>',
             f"<!-- {HEADER} -->",
             "<permissions>",
             f"    <privapp-permissions package={quoteattr(package)}>"]
    lines += [f"        <permission name={quoteattr(p)}/>"
              for p in sorted(perms)]
    lines += ["    </privapp-permissions>", "</permissions>", ""]
    with open(path, "w") as f:
        f.write("\n".join(lines))


def bp_list(items):
    return "[" + ", ".join(f'"{i}"' for i in items) + "]"


def split_uses_libs(libs):
    return (sorted(lib for lib, req in libs.items() if req),
            sorted(lib for lib, req in libs.items() if not req))


def gen_android_bp(modules, overrides, uses_libs, stubs, skip_checks):
    out = [f"// {HEADER}", ""]
    for name in sorted(modules, key=str.lower):
        entries = modules[name]
        e = entries[0]
        partition = PARTITIONS[e.partition]
        stub = name in stubs
        out.append("android_app_import {")
        out.append(f'    name: "{name}-Stub",' if stub else f'    name: "{name}",')
        universal = [x for x in entries if x.arch == "all"]
        if universal:
            out.append(f'    apk: "{apk_relpath(universal[0])}",')
        per_arch = [x for x in entries if x.arch != "all"]
        if per_arch:
            out.append("    arch: {")
            for x in sorted(per_arch, key=lambda x: ARCHES.index(x.arch)):
                out.append(f"        {x.arch}: {{")
                out.append(f'            apk: "{apk_relpath(x)}",')
                out.append("        },")
            out.append("    },")
        if e.cert == "presigned":
            # Keep the APK byte-for-byte, the v2+ signature covers the zip.
            out.append("    presigned: true,")
            out.append("    preprocessed: true,")
            # The APK can't be fixed up without breaking its signature, so
            # accept compressed JNI libs / priv-app dex. Apps that can't run
            # that way are listed in [stubs].
            if name in skip_checks:
                out.append("    skip_preprocessed_apk_checks: true,")
        elif e.cert != "default":
            out.append(f'    certificate: "{e.cert}",')
        if e.type == "priv":
            out.append("    privileged: true,")
        out.append(f"    {partition}: true,")
        out.append("    dex_preopt: {")
        out.append("        enabled: false,")
        out.append("    },")
        required, optional = split_uses_libs(uses_libs.get(name, {}))
        if required:
            out.append(f"    uses_libs: {bp_list(required)},")
        if optional:
            out.append(f"    optional_uses_libs: {bp_list(optional)},")
        if name in overrides:
            out.append(f"    overrides: {bp_list(overrides[name])},")
        if e.type == "priv":
            out.append(f"    required: {bp_list([privapp_module(name)])},")
        out.append("}")
        out.append("")
        out += gen_privapp_bp(name, e, partition)
    return "\n".join(out)


def gen_privapp_bp(name, e, partition):
    if e.type != "priv":
        return []
    return ["prebuilt_etc {",
            f'    name: "{privapp_module(name)}",',
            f'    src: "{privapp_relpath(name)}",',
            '    sub_dir: "permissions",',
            f"    {partition}: true,",
            "}",
            ""]


def privapp_module(name):
    return f"privapp-permissions-{name}.xml"


def gen_product_mk(modules, stubs):
    out = [f"# {HEADER}", "",
           "FDROID_PREBUILTS_PATH := "
           "$(patsubst %/,%,$(dir $(lastword $(MAKEFILE_LIST))))", "",
           "PRODUCT_PACKAGES += \\"]
    names = [n + "-Stub" if n in stubs else n
             for n in sorted(modules, key=str.lower)]
    out += [f"    {n}" + (" \\" if i < len(names) - 1 else "")
            for i, n in enumerate(names)]
    if stubs:
        # Presigned APKs with compressed JNI libs: <name>-Stub is installed
        # from Android.bp, PackageManager decompresses <name>.apk.gz to /data
        # on first boot (like on Android Go).
        out += ["", "PRODUCT_COPY_FILES += \\"]
        names = sorted(stubs, key=str.lower)
        for i, n in enumerate(names):
            e = modules[n][0]
            dest = f"{COPY_OUT[e.partition]}/{APP_DIRS[e.type]}/{n}/{n}.apk.gz"
            out.append(f"    $(FDROID_PREBUILTS_PATH)/{apk_relpath(e)}.gz:{dest}"
                       + (" \\" if i < len(names) - 1 else ""))
    return "\n".join(out) + "\n"


def write_if_changed(path, content):
    if os.path.exists(path):
        with open(path) as f:
            if f.read() == content:
                return
    with open(path, "w") as f:
        f.write(content)


def remove_stale(out_dir, keep):
    apps_dir = os.path.join(out_dir, "apps")
    if not os.path.isdir(apps_dir):
        return
    for root, dirs, files in os.walk(apps_dir, topdown=False):
        for fn in files:
            rel = os.path.relpath(os.path.join(root, fn), out_dir)
            if rel not in keep:
                os.remove(os.path.join(root, fn))
        if root != apps_dir and not os.listdir(root):
            os.rmdir(root)


def main():
    ap = argparse.ArgumentParser(description=__doc__)
    ap.add_argument("--list", default=os.path.join(
        os.path.dirname(os.path.abspath(__file__)), "repo", "fdroid.txt"),
        help="app list (default: repo/fdroid.txt)")
    ap.add_argument("--out", required=True,
                    help="output directory (the prebuilts repo checkout)")
    ap.add_argument("--summary", help="write a change summary to this file")
    args = ap.parse_args()
    sys.stdout.reconfigure(line_buffering=True)

    modules, overrides, stubs = parse_list(args.list)
    out_dir = os.path.abspath(args.out)
    os.makedirs(out_dir, exist_ok=True)
    lock_path = os.path.join(out_dir, "versions.txt")
    old_lock = read_lock(lock_path)
    new_lock = {}
    keep = set()
    changes = []
    uses_libs = {}
    skip_checks = set()

    with tempfile.TemporaryDirectory() as tmpdir:
        repos = {}
        for name in sorted(modules, key=str.lower):
            perms = set()
            fetched = []
            issues = {}
            for e in modules[name]:
                if e.repo not in repos:
                    repos[e.repo] = Repo(e.repo, tmpdir)
                repo = repos[e.repo]
                old = old_lock.get((e.name, e.arch))
                apk = pick_apk(repo, e, old and old["signer"])
                perms |= permissions_of(apk)

                rel = apk_relpath(e)
                dest = os.path.join(out_dir, rel)
                keep.add(rel)
                label = name if e.arch == "all" else f"{name} [{e.arch}]"
                version = f"{apk['versionName']} ({apk['versionCode']})"

                fresh = False
                if os.path.exists(dest) and sha256_file(dest) == apk["hash"]:
                    print(f"- {label}: {version} up to date")
                else:
                    fresh = True
                    print(f"- {label}: downloading {apk['apkName']}")
                    os.makedirs(os.path.dirname(dest), exist_ok=True)
                    part = dest + ".part"
                    digest = download(f"{repo.base}/{apk['apkName']}", part)
                    if digest != apk["hash"]:
                        os.remove(part)
                        die(f"{apk['apkName']}: sha256 {digest} does not "
                            f"match index {apk['hash']}")
                    os.replace(part, dest)
                    if old:
                        changes.append(f"{label}: {old['versionName']} "
                                       f"({old['versionCode']}) -> {version}")
                    else:
                        changes.append(f"{label}: add {version}")

                fetched.append((rel, fresh))
                if e.cert == "presigned":
                    issues[e.arch] = preprocessed_issue(dest, e.type == "priv")

                libs = uses_libs.setdefault(name, {})
                for lib, req in uses_libraries_of(dest).items():
                    libs[lib] = libs.get(lib, False) or req

                new_lock[(e.name, e.arch)] = {
                    "name": e.name, "arch": e.arch, "package": e.package,
                    "versionName": apk["versionName"],
                    "versionCode": str(apk["versionCode"]),
                    "signer": apk.get("signer", ""), "sha256": apk["hash"],
                    "repo": split_repo(e.repo)[0],
                }

            if any(issues.values()):
                skip_checks.add(name)
                print(f"  {name}: {', '.join(sorted(set(filter(None, issues.values()))))}"
                      f", skipping Soong's preprocessed APK checks")
                if not all(issues.values()):
                    # The property can't be set per arch.
                    warn(f"{name}: only some arches have preprocessed APK "
                         f"issues, the others will fail Soong's check")

            if name in stubs:
                for rel, fresh in fetched:
                    gz = os.path.join(out_dir, rel + ".gz")
                    keep.add(rel + ".gz")
                    if fresh or not os.path.exists(gz):
                        write_gz(os.path.join(out_dir, rel), gz)

            if modules[name][0].type == "priv":
                rel = privapp_relpath(name)
                keep.add(rel)
                write_privapp_xml(os.path.join(out_dir, rel),
                                  modules[name][0].package, perms)

    for key, old in sorted(old_lock.items()):
        if key not in new_lock:
            label = key[0] if key[1] == "all" else f"{key[0]} [{key[1]}]"
            changes.append(f"{label}: remove")

    remove_stale(out_dir, keep)
    write_if_changed(os.path.join(out_dir, "Android.bp"),
                     gen_android_bp(modules, overrides, uses_libs, stubs,
                                    skip_checks))
    write_if_changed(os.path.join(out_dir, "product.mk"),
                     gen_product_mk(modules, stubs))
    lock = [f"# {HEADER}", "#" + "\t".join(LOCK_FIELDS)]
    lock += ["\t".join(row[f] for f in LOCK_FIELDS)
             for _, row in sorted(new_lock.items())]
    write_if_changed(lock_path, "\n".join(lock) + "\n")

    print()
    print("\n".join(changes) if changes else "No APK changes.")
    if args.summary:
        with open(args.summary, "w") as f:
            f.write("\n".join(changes) + ("\n" if changes else ""))


if __name__ == "__main__":
    main()
